spring:
  profiles:
    active: dev
server:
  port: 8080
database:
  url: 'jdbc:mysql://127.0.0.1:3306/faithl'
  driver: 'org.postgresql.Driver'
  username: 'root'
  password: 'root'
sa-token:
  token-name: auth-token