spring:
  profiles:
    active: pro
database:
  url: 'jdbc:postgresql://127.0.0.1:5432/faithl'
  driver: 'org.postgresql.Driver'
  username: 'root'
  password: 'root'
sa-token:
  token-name: auth-token